### ISSUE TITLE
Please add more documentation.

### ISSUE THREAD

**Issue by greenSnot** [ringw/homer#2]
I am very excited & interested in this project ^_^

**Comment by ringw** [comment]
Thanks! There is a Google-internal rewrite of this project, which is better tested and documented. I'm working on getting it on GitHub as soon as possible. Will leave this open until it's released.

**Comment by greenSnot** [comment]
Wow, great! I am looking forward to it. Will it be an official project?

**Comment by ringw** [comment]
It's still just me so far, but I'm welcoming other contributors.

**Comment by javenfang** [comment]
@ringw How about the progress of Google internal rewrite's opening?    

I am looking forward to it very much!

**Comment by ringw** [comment]
Hey all,

I'm planning on releasing the rewrite on GitHub some time next month! Sorry for the delay, there has been some internal back and forth, but now I'm trying to get it open sourced quickly. However, it's still pre-alpha stage, only has a minimal CLI, and only has a rudimentary classifier that's not yet accurate enough to be useful.

**Comment by ringw** [comment]
I'm happy to announce that [Magenta OMR](https://github.com/ringw/magenta/tree/omr/magenta/models/omr) is now on GitHub! There is some more documentation that can be found through that README. It will be merged by [Magenta](https://github.com/tensorflow/magenta) soon.

**Comment by ringw** [comment]
Actually, we are now "Moonlight OMR": https://github.com/tensorflow/moonlight
